/*
Copyright The k3sm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package guestinit

import (
	"fmt"
	"strings"

	guestv1 "k3sm.io/apis/guest/v1"
)

// Resolver limits every libc in a container image agrees on.
//
// These are not k3sm policy: they are the caps the resolvers themselves apply,
// and exceeding them is what makes a resolv.conf fail in ways that look like a
// DNS outage. glibc reads at most MAXNS nameservers and MAXDNSRCH search
// domains and truncates a search line at 256 bytes; musl reads at most 3
// nameservers and, critically, DISCARDS a malformed or over-long line rather
// than using the part it understood. So an over-long search line does not lose
// its tail on alpine — it loses the whole search list.
const (
	maxNameservers     = 3
	maxSearchDomains   = 6
	maxSearchLineBytes = 256
)

// EtcFiles are the pod-level /etc files rendered once and bound into every
// container (see EtcBinds). They are content, not paths: the executor writes
// them under EtcDir.
type EtcFiles struct {
	ResolvConf string
	Hosts      string
	Hostname   string
}

// RenderResolvConf renders the pod's DNS configuration MUSL-SAFELY and returns
// the file content plus any warnings the boot log should carry.
//
// Musl-safe means two concrete things:
//
//  1. The emitted search line never exceeds what a resolver will parse
//     (maxSearchDomains entries, maxSearchLineBytes total). Entries are dropped
//     from the TAIL, so the pod's own namespace domain — the one that resolves
//     a bare Service name — survives, and the most generic suffix is what is
//     lost. Dropping from the tail is the honest trade: a partial search list
//     resolves most names, whereas an over-long line resolves none on musl.
//
//  2. The search list is emitted in full, in order, and is never made
//     conditional on `options ndots`. Musl IGNORES ndots and behaves as if
//     ndots:1, so on alpine a relative name that already contains a dot
//     ("kubernetes.default") is tried as-is and never expanded through the
//     search list, while a single-label name ("kubernetes") is. That is a
//     property of the resolver, not something a renderer can fix; what the
//     renderer guarantees is that the search list itself is intact and legal,
//     so every name musl DOES expand resolves. The ndots option is still
//     emitted because glibc images depend on it.
//
// Order within each list is significant and preserved: it is query order.
func RenderResolvConf(rc *guestv1.ResolvConf) (string, []string) {
	var (
		b        strings.Builder
		warnings []string
	)
	b.WriteString("# Generated by k3sm guest init. Do not edit: this file is a read-only bind.\n")

	ns := rc.GetNameservers()
	if len(ns) > maxNameservers {
		warnings = append(warnings, fmt.Sprintf(
			"resolv.conf: %d nameservers exceeds the resolver limit of %d; dropped %v",
			len(ns), maxNameservers, ns[maxNameservers:]))
		ns = ns[:maxNameservers]
	}
	for _, s := range ns {
		b.WriteString("nameserver " + s + "\n")
	}

	search, dropped := truncateSearch(rc.GetSearches())
	if len(dropped) > 0 {
		warnings = append(warnings, fmt.Sprintf(
			"resolv.conf: search list truncated to fit the resolver limits (%d domains, %d bytes); dropped %v",
			maxSearchDomains, maxSearchLineBytes, dropped))
	}
	if len(search) > 0 {
		b.WriteString("search " + strings.Join(search, " ") + "\n")
	}

	if opts := rc.GetOptions(); len(opts) > 0 {
		b.WriteString("options " + strings.Join(opts, " ") + "\n")
	}
	return b.String(), warnings
}

// truncateSearch returns the longest head of searches that fits both resolver
// limits, and the entries it dropped.
func truncateSearch(searches []string) (kept, dropped []string) {
	kept = searches
	if len(kept) > maxSearchDomains {
		dropped = append(dropped, kept[maxSearchDomains:]...)
		kept = kept[:maxSearchDomains]
	}
	for len(kept) > 0 && len("search "+strings.Join(kept, " ")+"\n") > maxSearchLineBytes {
		dropped = append([]string{kept[len(kept)-1]}, dropped...)
		kept = kept[:len(kept)-1]
	}
	return kept, dropped
}

// RenderHosts renders /etc/hosts for the pod. guestIP is the DHCP-leased
// address; it is empty at plan time (the lease is taken later in the boot), in
// which case only the loopback entries are written and the executor re-renders
// once the lease is held.
func RenderHosts(hostname, guestIP string) string {
	var b strings.Builder
	b.WriteString("# Generated by k3sm guest init. Do not edit: this file is a read-only bind.\n")
	b.WriteString("127.0.0.1\tlocalhost\n")
	b.WriteString("::1\tlocalhost ip6-localhost ip6-loopback\n")
	b.WriteString("fe00::0\tip6-localnet\n")
	b.WriteString("ff00::0\tip6-mcastprefix\n")
	b.WriteString("ff02::1\tip6-allnodes\n")
	b.WriteString("ff02::2\tip6-allrouters\n")
	if guestIP != "" && hostname != "" {
		b.WriteString(guestIP + "\t" + hostname + "\n")
	}
	return b.String()
}

// RenderHostname renders /etc/hostname.
func RenderHostname(hostname string) string { return hostname + "\n" }

// ParseMemTotal extracts MemTotal, in BYTES, from /proc/meminfo content. It
// lives here, as a pure parse over content the executor reads, so the unit
// conversion is covered by a darwin test rather than only by a cross-compile.
//
// A missing or unparseable MemTotal returns 0, which UpperSizeBytes reads as
// "unknown" and answers with its default — an unreadable meminfo must not turn
// into an unbounded overlay upper.
func ParseMemTotal(meminfo string) int64 {
	for _, line := range strings.Split(meminfo, "\n") {
		rest, ok := strings.CutPrefix(line, "MemTotal:")
		if !ok {
			continue
		}
		fields := strings.Fields(rest)
		if len(fields) == 0 {
			return 0
		}
		var kb int64
		if _, err := fmt.Sscanf(fields[0], "%d", &kb); err != nil || kb <= 0 {
			return 0
		}
		if len(fields) > 1 && !strings.EqualFold(fields[1], "kB") {
			return 0
		}
		return kb * 1024
	}
	return 0
}
