/*
Copyright The k3sm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
 * Code generated by k3sm.io/runtimed/pkg/shadowset/gen. DO NOT EDIT.
 *
 * The host exec paths the node keeps a re-signed copy for, and the copy each
 * maps to (a file name under K3SM_SHADOW_DIR). The list is declared in
 * pkg/shadowset; edit it there and run go generate ./pkg/shadowset.
 */

#ifndef K3SM_SHADOW_TABLE_H
#define K3SM_SHADOW_TABLE_H

/* The longest copy name, in bytes. */
#define K3SM_SHADOW_COPY_MAX 8

static const struct {
    const char *host;
    const char *copy;
} k3sm_shadow_map[] = {
    {"/bin/sh", "bash"},
    {"/bin/bash", "bash"},
    {"/bin/zsh", "zsh"},
    {"/bin/dash", "dash"},
    {"/usr/bin/env", "env"},
    {"/usr/bin/tar", "tar"},
    {"/usr/bin/bsdtar", "tar"},
    {"/bin/cat", "cat"},
    {"/bin/cp", "cp"},
    {"/bin/mv", "mv"},
    {"/bin/ls", "ls"},
    {"/bin/mkdir", "mkdir"},
    {"/bin/rm", "rm"},
    {"/bin/chmod", "chmod"},
    {"/bin/ln", "ln"},
    {"/bin/echo", "echo"},
    {"/bin/test", "test"},
    {"/bin/[", "test"},
    {"/bin/sleep", "sleep"},
    {"/bin/date", "date"},
    {"/usr/bin/sed", "sed"},
    {"/usr/bin/grep", "grep"},
    {"/usr/bin/egrep", "grep"},
    {"/usr/bin/zgrep", "grep"},
    {"/usr/bin/fgrep", "fgrep"},
    {"/usr/bin/awk", "awk"},
    {"/usr/bin/tee", "tee"},
    {"/usr/bin/head", "head"},
    {"/usr/bin/tail", "tail"},
    {"/usr/bin/wc", "wc"},
    {"/usr/bin/sort", "sort"},
    {"/usr/bin/basename", "basename"},
    {"/usr/bin/dirname", "dirname"},
    {"/usr/bin/find", "find"},
    {"/usr/bin/xargs", "xargs"},
    {"/usr/bin/cut", "cut"},
    {"/usr/bin/tr", "tr"},
    {"/usr/bin/touch", "touch"},
    {"/usr/bin/stat", "stat"},
    {"/usr/bin/readlink", "readlink"},
    {"/usr/bin/gzip", "gzip"},
    {"/usr/bin/gunzip", "gunzip"},
    {"/usr/bin/zcat", "gunzip"},
    {"/usr/bin/base64", "base64"},
};

#endif /* K3SM_SHADOW_TABLE_H */
